
name: Rubocop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    env:
      CODECOV_TOKEN: "8314c388-54a3-4125-915b-3d4836c15b29"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3 # Not needed with a .ruby-version file
          bundler-cache: true # # runs 'bundle install' and caches installed gems automatically
      - run: |
          gem update --system
          gem install bundler
          bundle update --jobs 4 --retry 3
          bundle exec rubocop
